---
plugin: ['left_right']  #Algorithm to be used for generating similarity scores
selection_algorithm : 'HighestMatch'  #This algorithm is used to classify the image to particular class using similarity scores of different plugins Highest Average Match: obtained by averaging over similarity score for different plugins for each class. From resulting scores the class with highest score is considered to be label fo that image
src_data_mode : 'local' #Set this field "local"(case sensitive) if images need to be labled are already downloaded in a folder in local machine if you want to download from url put any random string
src_data_url : #'https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse1.mm.bing.net%2Fth%3Fid%3DOIP.oun_JdJAfeVDKkjdv_X4rgHaE8%26pid%3DApi&f=1'        #URL to dowload image from (only of src_data_mode is not local)
src_data_path : 'test_data' #Folder name where images that need to be labeled are stored
ref_data_path : 'ref_images/tennis' #Path for reference images to calculate similarity scores for each class
save_data_path : 'buckets/tennis' #Path where newly labeled images from src_data_path should be stored
confidence_level : 80
margin_of_error : 0.1